name: buildAndRun
run-name: ${{ github.actor }} building and test project
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Show tree
        run: tree
      - name: CD App
        run: cd App
      - name: Build with Gradle
        run: ./gradlew build
